### ISSUE TITLE
UsesColumnNumber mapping doesn't seem to work..

### ISSUE THREAD

**Issue by Samwards** [ChrisHodges/ExcelToEnumerable#1]
I'm attempting to map various columns to a large spreadsheet. Initially, I was using 'UsesColumnNamed' however, with number of columns and manual input nature of this spreadsheet this proved to be difficult to manage consistently.  So I've tried to use the UsesColumnNumber instead, but now I'm receiving:

"ExcelToEnumerable.Exceptions.ExcelToEnumerableInvalidHeaderException: 'Missing headers" and Missing Properties for the entire collection.

**Comment by ChrisHodges** [comment]
You should use `.UsingHeaderNames(false)` in conjuction with `.UsesColumnNumber` and also ensure that every property in your class is either mapped to a column or explicitly ignored using `Ignore()`. If you do that in your config do you still get the exception?

**Comment by ChrisHodges** [comment]
FYI in version 0.3.0 I've improved the error messaging so that if you forget to map or ignore one of your properties you'll get an `ExcelToEnumerableConfigException` informing you of the problem.

**Comment by ChrisHodges** [comment]
Have closed this issue in light of improved messaging in version 0.3.0
