### ISSUE TITLE
MapToColumnNamed is not available

### ISSUE THREAD

**Issue by denis-reichelt** [ChrisHodges/ExcelToEnumerable#12]
Following the examples there should be an option on the Property<> to map a member to a specific named column called "MapToColumnNamed(...)".
Obviously there is no such a Method available:

![image](https://user-images.githubusercontent.com/13780880/109146116-afcf5400-7763-11eb-9b1f-e0642cfdcafc.png)

**Comment by ChrisHodges** [comment]
Hi denis-reichelt. Thanks for raising this issue. The method has been renamed `UsesColumnNamed` but the documentation wasn't updated. I've now fixed the readme. Feel free to close this issue if you regard it as resolved or add another comment if not.

**Comment by denis-reichelt** [comment]
I found it. Thanks !
