### ISSUE TITLE
Typo in Example

### ISSUE THREAD

**Issue by aodennison** [ChrisHodges/ExcelToEnumerable#2]
In a Simple Example (https://github.com/ChrisHodges/ExcelToEnumerable)
The .xslsx column heading should be "**Name**", not "**Animal**"
Since the first member in Animal class is `public string Name { get; set; }`

Note the member cannot be "Animal",  since that is the class name.

**Comment by ChrisHodges** [comment]
Well spotted and thanks for reporting. I've updated the readme.
