### ISSUE TITLE
Dependency for .net core 3.1 fails

### ISSUE THREAD

**Issue by UkeHa** [ChrisHodges/ExcelToEnumerable#4]
When trying to add ExcelToEnumerable to a new dotnet core 3.1 application it fails due to a package downgrade.

"Package restore failed. Rolling back package changes for 'MyProgram'. Detected package downgrade: System.IO.Compression from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version."

Adding the correct forced reference to the projects .csproj solves this.
```
<ItemGroup>
		<PackageReference Include="System.IO.Compression" Version="4.3.0" />
</ItemGroup>
```

**Comment by ChrisHodges** [comment]
I've upgraded the [ExcelNumberFormat](https://www.nuget.org/packages/ExcelNumberFormat/) dependency in **LightweightExcelReader** and I can now add the library to a .Net Core 3.1 package without a problem. Let me know if that's working for you too and I'll close the issue.

**Comment by UkeHa** [comment]
works as intended!
