### ISSUE TITLE
Support user reflection use-cases.

### ISSUE THREAD

**Issue by rwoodley** [ChrisHodges/ExcelToEnumerable#7]
I have numerous spread-sheets all in different formats that need to be read on a daily basis. I want to use annotations to mark-up the POCO class instead of coding this info in the .ExcelToEnumerable lambda.

So for example I could annotate my class like this:
```
class MyExcelMappingClass
{
	[ColumnNameAttribute(Name = "Some Weird Column Header")] 
	public string ActualName { get; set; }

	// Many other Properties with weird column headers.
 }

```

And then, using reflection, loop over the annotations and properties, e.g.:
```
IEnumerable<MyExcelMappingClass> myList = "SampleSpreadsheet.xlsx"
		.ExcelToEnumerable<MyExcelMappingClass>(
		x =>
		{
			foreach (var prop in typeof(MyExcelMappingClass).GetProperties().AsEnumerable())
			{
				object[] attrs = prop.GetCustomAttributes(true);
				if (prop.PropertyType == typeof(string))
					x.Property<string>(prop.Name).MapsToColumnNamed(((ColumnNameAttribute)attrs[0]).Name);
				else if (prop.PropertyType == typeof(double))
					x.Property<double>(prop.Name).MapsToColumnNamed(((ColumnNameAttribute)attrs[0]).Name);
				else
					throw new NotImplementedException(prop.PropertyType.ToString());
			}

		})
	;

```

The only problem is, `Property()` does not have a signature taking a string. I tried shoe-horning this into the Expression signature, but couldn't get it to work. Even if I could the code would not be very intuitive or elegant. 

So adding a signature that takes the property name directly allows users to have more complicated scenarios, for instance as out-lined above.

**Comment by ChrisHodges** [comment]
Hi rwoodley. Thanks for this, it's a great contribution. I'm happy to merge in but could I ask that you submit a new PR, simply because I've setup a new Contributor Licence Agreement and if you submit a new PR with the same changes it should allow you to agree to the CLA through https://cla-assistant.io ?

**Comment by ChrisHodges** [comment]
I've not heard back from you regarding the contributor licences agreement so I'm going to go ahead and close this. Thanks.
